# Private Config Extension for Docker Compose.

services:

  #################
  ### Minecraft ###
  #################

  proxy:
    environment:
      SYNC_SKIP_NEWER_IN_DESTINATION: "true"

  paper:
    environment:
      # Any Jars need to be here, comma separated so that they are not removed during sync
      REMOVE_OLD_MODS_EXCLUDE: "Vulcan.jar,packetevents-spigot-2.10.1.jar"
      SYNC_SKIP_NEWER_IN_DESTINATION: "true"

  pvp:
    environment:
      # Any Jars need to be here, comma separated so that they are not removed during sync
      REMOVE_OLD_MODS_EXCLUDE: "Vulcan.jar,packetevents-spigot-2.10.1.jar"
      SYNC_SKIP_NEWER_IN_DESTINATION: "true"
